name    'WhatsARanjit-plexmediaserver'
version '0.2.0'
source 'https://github.com/WhatsARanjit/plex-media-server'
author 'Ranjit Viswakumar'
license 'Apache License, Version 2.0'
summary 'This module installs and manages Plex Media Server'
description 'Only compatible on *NIX systems'
project_page 'https://github.com/WhatsARanjit/plex-media-server'
